[2024-12-08T09:09:06.278+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-08T09:09:06.301+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: IMDB_testing_DAG.load manual__2024-12-08T09:08:55.676019+00:00 [queued]>
[2024-12-08T09:09:06.317+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: IMDB_testing_DAG.load manual__2024-12-08T09:08:55.676019+00:00 [queued]>
[2024-12-08T09:09:06.318+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2024-12-08T09:09:06.341+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load> on 2024-12-08 09:08:55.676019+00:00
[2024-12-08T09:09:06.357+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1060) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-08T09:09:06.357+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'IMDB_testing_DAG', 'load', 'manual__2024-12-08T09:08:55.676019+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpm3x_h023']
[2024-12-08T09:09:06.360+0000] {standard_task_runner.py:72} INFO - Started process 1082 to run task
[2024-12-08T09:09:06.361+0000] {standard_task_runner.py:105} INFO - Job 128: Subtask load
[2024-12-08T09:09:06.478+0000] {task_command.py:467} INFO - Running <TaskInstance: IMDB_testing_DAG.load manual__2024-12-08T09:08:55.676019+00:00 [running]> on host 9936f60771cc
[2024-12-08T09:09:06.613+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='IMDB_testing_DAG' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-12-08T09:08:55.676019+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-08T09:08:55.676019+00:00'
[2024-12-08T09:09:06.616+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-08T09:09:06.617+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-08T09:09:06.618+0000] {logging_mixin.py:190} INFO - Current task name:load state:running start_date:2024-12-08 09:09:06.302647+00:00
[2024-12-08T09:09:06.619+0000] {logging_mixin.py:190} INFO - Dag name:IMDB_testing_DAG and current dag run status:running
[2024-12-08T09:09:06.619+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-08T09:09:06.863+0000] {logging_mixin.py:190} INFO - A error Occured while loading dim_genre (psycopg2.errors.SyntaxError) syntax error at or near "dim_genre"
LINE 2:                     MERGE dim_genre as D
                                  ^

[SQL:  
                    MERGE dim_genre as D
                    USING temp_dim_genre as S
                    ON 
                        D.genre_id = S.genre_id
                    WHEN MATCHED THEN 
                        UPDATE SET 
                            D.genre = S.genre,
                            D.genre_id = S.genre_id
                            
    
                    WHEN NOT MATCHED BY TARGET THEN 
                        INSERT (genre, genre_id) 
                        VALUES (S.genre, S.genre_id);
                ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-12-08T09:09:06.870+0000] {logging_mixin.py:190} INFO - An error Occured while loading dim_country (psycopg2.errors.SyntaxError) syntax error at or near "dim_country"
LINE 2:                     MERGE dim_country as D
                                  ^

[SQL:  
                    MERGE dim_country as D
                    USING temp_dim_country as S
                    ON 
                        D.country_id = S.country_id
                    WHEN MATCHED THEN 
                        UPDATE SET 
                            D.country = S.country,
                            D.country_id = S.country_id
                            
    
                    WHEN NOT MATCHED BY TARGET THEN 
                        INSERT (country, country_id) 
                        VALUES (S.country, S.country_id);
                ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-12-08T09:09:06.876+0000] {logging_mixin.py:190} INFO - An error occured while loading dim_director {e}
[2024-12-08T09:09:06.884+0000] {logging_mixin.py:190} INFO - An error occured while loading dim_details {e}
[2024-12-08T09:09:06.891+0000] {logging_mixin.py:190} INFO - An error occured while loading fact_table {e}
[2024-12-08T09:09:06.892+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-08T09:09:06.907+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-08T09:09:06.908+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=IMDB_testing_DAG, task_id=load, run_id=manual__2024-12-08T09:08:55.676019+00:00, execution_date=20241208T090855, start_date=20241208T090906, end_date=20241208T090906
[2024-12-08T09:09:06.928+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-08T09:09:06.929+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-08T09:09:06.930+0000] {logging_mixin.py:190} INFO - Dag name:IMDB_testing_DAG queued_at:2024-12-08 09:08:55.699814+00:00
[2024-12-08T09:09:06.931+0000] {logging_mixin.py:190} INFO - Task hostname:9936f60771cc operator:PythonOperator
[2024-12-08T09:09:06.946+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-08T09:09:06.971+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-08T09:09:06.975+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
