[2024-12-02T09:41:55.700+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-02T09:41:55.719+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: IMDB_testing_DAG.transform manual__2024-12-02T09:37:44.477733+00:00 [queued]>
[2024-12-02T09:41:55.732+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: IMDB_testing_DAG.transform manual__2024-12-02T09:37:44.477733+00:00 [queued]>
[2024-12-02T09:41:55.733+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 3
[2024-12-02T09:41:55.750+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform> on 2024-12-02 09:37:44.477733+00:00
[2024-12-02T09:41:55.761+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=56804) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-02T09:41:55.761+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'IMDB_testing_DAG', 'transform', 'manual__2024-12-02T09:37:44.477733+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp4w8goalv']
[2024-12-02T09:41:55.763+0000] {standard_task_runner.py:72} INFO - Started process 56805 to run task
[2024-12-02T09:41:55.763+0000] {standard_task_runner.py:105} INFO - Job 72: Subtask transform
[2024-12-02T09:41:55.813+0000] {task_command.py:467} INFO - Running <TaskInstance: IMDB_testing_DAG.transform manual__2024-12-02T09:37:44.477733+00:00 [running]> on host a34e3ee3c8c3
[2024-12-02T09:41:55.903+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='IMDB_testing_DAG' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T09:37:44.477733+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-02T09:37:44.477733+00:00'
[2024-12-02T09:41:55.905+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-02T09:41:55.906+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-02T09:41:55.907+0000] {logging_mixin.py:190} INFO - Current task name:transform state:running start_date:2024-12-02 09:41:55.720449+00:00
[2024-12-02T09:41:55.907+0000] {logging_mixin.py:190} INFO - Dag name:IMDB_testing_DAG and current dag run status:running
[2024-12-02T09:41:55.908+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-02T09:41:56.042+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/app/src/transform/transform.py", line 122, in transform
    fact_movie = create_fact_table(null_handled_df, dim_tables, merge_keys, drop_columns)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/app/src/transform/transform.py", line 87, in create_fact_table
    df.drop(columns = [drop_columns],inplace = True)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 5344, in drop
    return super().drop(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4711, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4753, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 7000, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: "[('title_x', 'type_x', 'certificate_rating_x', 'country', 'director', 'productionBudget_currency', 'worldwideGross_currency', 'genre', 'title_y', 'type_y', 'certificate_rating_y')] not found in axis"
[2024-12-02T09:41:56.071+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-02T09:41:56.073+0000] {logging_mixin.py:190} INFO - Task start:2024-12-02 09:41:55.720449+00:00 end:2024-12-02 09:41:56.071181+00:00 duration:0.350732
[2024-12-02T09:41:56.074+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform> dag:<DAG: IMDB_testing_DAG> dagrun:<DagRun IMDB_testing_DAG @ 2024-12-02 09:37:44.477733+00:00: manual__2024-12-02T09:37:44.477733+00:00, state:running, queued_at: 2024-12-02 09:37:44.512805+00:00. externally triggered: True>
[2024-12-02T09:41:56.075+0000] {logging_mixin.py:190} INFO - Failure caused by "[('title_x', 'type_x', 'certificate_rating_x', 'country', 'director', 'productionBudget_currency', 'worldwideGross_currency', 'genre', 'title_y', 'type_y', 'certificate_rating_y')] not found in axis"
[2024-12-02T09:41:56.076+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=IMDB_testing_DAG, task_id=transform, run_id=manual__2024-12-02T09:37:44.477733+00:00, execution_date=20241202T093744, start_date=20241202T094155, end_date=20241202T094156
[2024-12-02T09:41:56.090+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-02T09:41:56.091+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 72 for task transform ("[('title_x', 'type_x', 'certificate_rating_x', 'country', 'director', 'productionBudget_currency', 'worldwideGross_currency', 'genre', 'title_y', 'type_y', 'certificate_rating_y')] not found in axis"; 56805)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/app/src/transform/transform.py", line 122, in transform
    fact_movie = create_fact_table(null_handled_df, dim_tables, merge_keys, drop_columns)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/app/src/transform/transform.py", line 87, in create_fact_table
    df.drop(columns = [drop_columns],inplace = True)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 5344, in drop
    return super().drop(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4711, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4753, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 7000, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: "[('title_x', 'type_x', 'certificate_rating_x', 'country', 'director', 'productionBudget_currency', 'worldwideGross_currency', 'genre', 'title_y', 'type_y', 'certificate_rating_y')] not found in axis"
[2024-12-02T09:41:56.112+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-02T09:41:56.138+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-02T09:41:56.145+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
