[2024-12-02T10:10:24.812+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-02T10:10:24.846+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: IMDB_testing_DAG.load manual__2024-12-02T10:10:06.096207+00:00 [queued]>
[2024-12-02T10:10:24.867+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: IMDB_testing_DAG.load manual__2024-12-02T10:10:06.096207+00:00 [queued]>
[2024-12-02T10:10:24.869+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2024-12-02T10:10:24.903+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load> on 2024-12-02 10:10:06.096207+00:00
[2024-12-02T10:10:24.919+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=73311) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-02T10:10:24.922+0000] {standard_task_runner.py:72} INFO - Started process 73327 to run task
[2024-12-02T10:10:24.928+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'IMDB_testing_DAG', 'load', 'manual__2024-12-02T10:10:06.096207+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpy2jg98z1']
[2024-12-02T10:10:24.932+0000] {standard_task_runner.py:105} INFO - Job 85: Subtask load
[2024-12-02T10:10:25.050+0000] {task_command.py:467} INFO - Running <TaskInstance: IMDB_testing_DAG.load manual__2024-12-02T10:10:06.096207+00:00 [running]> on host a34e3ee3c8c3
[2024-12-02T10:10:25.182+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='IMDB_testing_DAG' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T10:10:06.096207+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-02T10:10:06.096207+00:00'
[2024-12-02T10:10:25.185+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-02T10:10:25.186+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-02T10:10:25.187+0000] {logging_mixin.py:190} INFO - Current task name:load state:running start_date:2024-12-02 10:10:24.847495+00:00
[2024-12-02T10:10:25.188+0000] {logging_mixin.py:190} INFO - Dag name:IMDB_testing_DAG and current dag run status:running
[2024-12-02T10:10:25.190+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-02T10:10:25.324+0000] {logging_mixin.py:190} INFO - A error Occured while loading dim_genre (psycopg2.errors.SyntaxError) syntax error at or near "dim_genre"
LINE 2:                     MERGE dim_genre as D
                                  ^

[SQL:  
                    MERGE dim_genre as D
                    USING temp_dim_genre as S
                    ON 
                        D.genre_id = S.genre_id
                    WHEN MATCHED THEN 
                        UPDATE SET 
                            D.genre = S.genre,
                            D.genre_id = S.genre_id
                            
    
                    WHEN NOT MATCHED BY TARGET THEN 
                        INSERT (genre, genre_id) 
                        VALUES (S.genre, S.genre_id);
                ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-12-02T10:10:25.334+0000] {logging_mixin.py:190} INFO - An error Occured while loading dim_country (psycopg2.errors.SyntaxError) syntax error at or near "dim_country"
LINE 2:                     MERGE dim_country as D
                                  ^

[SQL:  
                    MERGE dim_country as D
                    USING temp_dim_country as S
                    ON 
                        D.country_id = S.country_id
                    WHEN MATCHED THEN 
                        UPDATE SET 
                            D.country = S.country,
                            D.country_id = S.country_id
                            
    
                    WHEN NOT MATCHED BY TARGET THEN 
                        INSERT (country, country_id) 
                        VALUES (S.country, S.country_id);
                ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-12-02T10:10:25.342+0000] {logging_mixin.py:190} INFO - An error occured while loading dim_director {e}
[2024-12-02T10:10:25.352+0000] {logging_mixin.py:190} INFO - An error occured while loading dim_details {e}
[2024-12-02T10:10:25.363+0000] {logging_mixin.py:190} INFO - An error occured while loading fact_table {e}
[2024-12-02T10:10:25.364+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-02T10:10:25.379+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-02T10:10:25.381+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=IMDB_testing_DAG, task_id=load, run_id=manual__2024-12-02T10:10:06.096207+00:00, execution_date=20241202T101006, start_date=20241202T101024, end_date=20241202T101025
[2024-12-02T10:10:25.397+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-02T10:10:25.398+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-02T10:10:25.399+0000] {logging_mixin.py:190} INFO - Dag name:IMDB_testing_DAG queued_at:2024-12-02 10:10:06.390632+00:00
[2024-12-02T10:10:25.400+0000] {logging_mixin.py:190} INFO - Task hostname:a34e3ee3c8c3 operator:PythonOperator
[2024-12-02T10:10:25.427+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-02T10:10:25.450+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-02T10:10:25.455+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
