[2024-12-08T09:08:32.460+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-08T09:08:32.498+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: IMDB_testing_DAG.load scheduled__2024-12-03T00:00:00+00:00 [queued]>
[2024-12-08T09:08:32.531+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: IMDB_testing_DAG.load scheduled__2024-12-03T00:00:00+00:00 [queued]>
[2024-12-08T09:08:32.535+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2024-12-08T09:08:32.579+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load> on 2024-12-03 00:00:00+00:00
[2024-12-08T09:08:32.602+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=673) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-08T09:08:32.605+0000] {standard_task_runner.py:72} INFO - Started process 731 to run task
[2024-12-08T09:08:32.604+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'IMDB_testing_DAG', 'load', 'scheduled__2024-12-03T00:00:00+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpv68lwvl6']
[2024-12-08T09:08:32.607+0000] {standard_task_runner.py:105} INFO - Job 125: Subtask load
[2024-12-08T09:08:32.737+0000] {task_command.py:467} INFO - Running <TaskInstance: IMDB_testing_DAG.load scheduled__2024-12-03T00:00:00+00:00 [running]> on host 9936f60771cc
[2024-12-08T09:08:33.017+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='IMDB_testing_DAG' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-03T00:00:00+00:00'
[2024-12-08T09:08:33.028+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-08T09:08:33.029+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-08T09:08:33.031+0000] {logging_mixin.py:190} INFO - Current task name:load state:running start_date:2024-12-08 09:08:32.501820+00:00
[2024-12-08T09:08:33.034+0000] {logging_mixin.py:190} INFO - Dag name:IMDB_testing_DAG and current dag run status:running
[2024-12-08T09:08:33.036+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-08T09:08:33.390+0000] {logging_mixin.py:190} INFO - A error Occured while loading dim_genre (psycopg2.errors.SyntaxError) syntax error at or near "dim_genre"
LINE 2:                     MERGE dim_genre as D
                                  ^

[SQL:  
                    MERGE dim_genre as D
                    USING temp_dim_genre as S
                    ON 
                        D.genre_id = S.genre_id
                    WHEN MATCHED THEN 
                        UPDATE SET 
                            D.genre = S.genre,
                            D.genre_id = S.genre_id
                            
    
                    WHEN NOT MATCHED BY TARGET THEN 
                        INSERT (genre, genre_id) 
                        VALUES (S.genre, S.genre_id);
                ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-12-08T09:08:33.424+0000] {logging_mixin.py:190} INFO - An error Occured while loading dim_country (psycopg2.errors.SyntaxError) syntax error at or near "dim_country"
LINE 2:                     MERGE dim_country as D
                                  ^

[SQL:  
                    MERGE dim_country as D
                    USING temp_dim_country as S
                    ON 
                        D.country_id = S.country_id
                    WHEN MATCHED THEN 
                        UPDATE SET 
                            D.country = S.country,
                            D.country_id = S.country_id
                            
    
                    WHEN NOT MATCHED BY TARGET THEN 
                        INSERT (country, country_id) 
                        VALUES (S.country, S.country_id);
                ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-12-08T09:08:33.466+0000] {logging_mixin.py:190} INFO - An error occured while loading dim_director {e}
[2024-12-08T09:08:33.486+0000] {logging_mixin.py:190} INFO - An error occured while loading dim_details {e}
[2024-12-08T09:08:33.501+0000] {logging_mixin.py:190} INFO - An error occured while loading fact_table {e}
[2024-12-08T09:08:33.503+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-08T09:08:33.540+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-08T09:08:33.542+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=IMDB_testing_DAG, task_id=load, run_id=scheduled__2024-12-03T00:00:00+00:00, execution_date=20241203T000000, start_date=20241208T090832, end_date=20241208T090833
[2024-12-08T09:08:33.580+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-08T09:08:33.582+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-08T09:08:33.585+0000] {logging_mixin.py:190} INFO - Dag name:IMDB_testing_DAG queued_at:2024-12-08 09:07:47.900594+00:00
[2024-12-08T09:08:33.587+0000] {logging_mixin.py:190} INFO - Task hostname:9936f60771cc operator:PythonOperator
[2024-12-08T09:08:33.650+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-08T09:08:33.693+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-08T09:08:33.698+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
