[2024-12-03T05:34:50.005+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T05:34:50.026+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: IMDB_testing_DAG.load manual__2024-12-03T05:34:38.738245+00:00 [queued]>
[2024-12-03T05:34:50.039+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: IMDB_testing_DAG.load manual__2024-12-03T05:34:38.738245+00:00 [queued]>
[2024-12-03T05:34:50.040+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2024-12-03T05:34:50.058+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load> on 2024-12-03 05:34:38.738245+00:00
[2024-12-03T05:34:50.069+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'IMDB_testing_DAG', 'load', 'manual__2024-12-03T05:34:38.738245+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmps6lqub6l']
[2024-12-03T05:34:50.069+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=21782) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-03T05:34:50.071+0000] {standard_task_runner.py:105} INFO - Job 110: Subtask load
[2024-12-03T05:34:50.071+0000] {standard_task_runner.py:72} INFO - Started process 21797 to run task
[2024-12-03T05:34:50.121+0000] {task_command.py:467} INFO - Running <TaskInstance: IMDB_testing_DAG.load manual__2024-12-03T05:34:38.738245+00:00 [running]> on host 1e8326103174
[2024-12-03T05:34:50.218+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='IMDB_testing_DAG' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T05:34:38.738245+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T05:34:38.738245+00:00'
[2024-12-03T05:34:50.221+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T05:34:50.222+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T05:34:50.223+0000] {logging_mixin.py:190} INFO - Current task name:load state:running start_date:2024-12-03 05:34:50.027396+00:00
[2024-12-03T05:34:50.223+0000] {logging_mixin.py:190} INFO - Dag name:IMDB_testing_DAG and current dag run status:running
[2024-12-03T05:34:50.225+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T05:34:50.420+0000] {logging_mixin.py:190} INFO - A error Occured while loading dim_genre (psycopg2.errors.SyntaxError) syntax error at or near "dim_genre"
LINE 2:                     MERGE dim_genre as D
                                  ^

[SQL:  
                    MERGE dim_genre as D
                    USING temp_dim_genre as S
                    ON 
                        D.genre_id = S.genre_id
                    WHEN MATCHED THEN 
                        UPDATE SET 
                            D.genre = S.genre,
                            D.genre_id = S.genre_id
                            
    
                    WHEN NOT MATCHED BY TARGET THEN 
                        INSERT (genre, genre_id) 
                        VALUES (S.genre, S.genre_id);
                ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-12-03T05:34:50.424+0000] {logging_mixin.py:190} INFO - An error Occured while loading dim_country (psycopg2.errors.SyntaxError) syntax error at or near "dim_country"
LINE 2:                     MERGE dim_country as D
                                  ^

[SQL:  
                    MERGE dim_country as D
                    USING temp_dim_country as S
                    ON 
                        D.country_id = S.country_id
                    WHEN MATCHED THEN 
                        UPDATE SET 
                            D.country = S.country,
                            D.country_id = S.country_id
                            
    
                    WHEN NOT MATCHED BY TARGET THEN 
                        INSERT (country, country_id) 
                        VALUES (S.country, S.country_id);
                ]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-12-03T05:34:50.428+0000] {logging_mixin.py:190} INFO - An error occured while loading dim_director {e}
[2024-12-03T05:34:50.432+0000] {logging_mixin.py:190} INFO - An error occured while loading dim_details {e}
[2024-12-03T05:34:50.436+0000] {logging_mixin.py:190} INFO - An error occured while loading fact_table {e}
[2024-12-03T05:34:50.437+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T05:34:50.448+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T05:34:50.449+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=IMDB_testing_DAG, task_id=load, run_id=manual__2024-12-03T05:34:38.738245+00:00, execution_date=20241203T053438, start_date=20241203T053450, end_date=20241203T053450
[2024-12-03T05:34:50.459+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-03T05:34:50.459+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-03T05:34:50.460+0000] {logging_mixin.py:190} INFO - Dag name:IMDB_testing_DAG queued_at:2024-12-03 05:34:38.817083+00:00
[2024-12-03T05:34:50.462+0000] {logging_mixin.py:190} INFO - Task hostname:1e8326103174 operator:PythonOperator
[2024-12-03T05:34:50.497+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T05:34:50.520+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T05:34:50.524+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
