[2024-12-02T08:23:09.616+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-02T08:23:09.638+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: IMDB_testing_DAG.transform manual__2024-12-02T08:23:03.329268+00:00 [queued]>
[2024-12-02T08:23:09.655+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: IMDB_testing_DAG.transform manual__2024-12-02T08:23:03.329268+00:00 [queued]>
[2024-12-02T08:23:09.656+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2024-12-02T08:23:09.675+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform> on 2024-12-02 08:23:03.329268+00:00
[2024-12-02T08:23:09.690+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'IMDB_testing_DAG', 'transform', 'manual__2024-12-02T08:23:03.329268+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpv1fvcako']
[2024-12-02T08:23:09.691+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=11124) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-02T08:23:09.693+0000] {standard_task_runner.py:105} INFO - Job 54: Subtask transform
[2024-12-02T08:23:09.693+0000] {standard_task_runner.py:72} INFO - Started process 11165 to run task
[2024-12-02T08:23:09.756+0000] {task_command.py:467} INFO - Running <TaskInstance: IMDB_testing_DAG.transform manual__2024-12-02T08:23:03.329268+00:00 [running]> on host a34e3ee3c8c3
[2024-12-02T08:23:09.879+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='IMDB_testing_DAG' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T08:23:03.329268+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-02T08:23:03.329268+00:00'
[2024-12-02T08:23:09.882+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-02T08:23:09.884+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-02T08:23:09.885+0000] {logging_mixin.py:190} INFO - Current task name:transform state:running start_date:2024-12-02 08:23:09.639638+00:00
[2024-12-02T08:23:09.886+0000] {logging_mixin.py:190} INFO - Dag name:IMDB_testing_DAG and current dag run status:running
[2024-12-02T08:23:09.887+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-02T08:23:10.042+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/app/src/transform/transform.py", line 106, in transform
    rename_selected_df = rename_column(df)
                         ^^^^^^^^^^^^^^^^^
  File "/opt/airflow/app/src/transform/transform.py", line 17, in rename_column
    rename_selected_df = df[columns].copy()
                         ~~^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6179, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['genres_genres_6_text'] not in index"
[2024-12-02T08:23:10.089+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-02T08:23:10.090+0000] {logging_mixin.py:190} INFO - Task start:2024-12-02 08:23:09.639638+00:00 end:2024-12-02 08:23:10.088659+00:00 duration:0.449021
[2024-12-02T08:23:10.091+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform> dag:<DAG: IMDB_testing_DAG> dagrun:<DagRun IMDB_testing_DAG @ 2024-12-02 08:23:03.329268+00:00: manual__2024-12-02T08:23:03.329268+00:00, state:running, queued_at: 2024-12-02 08:23:03.407740+00:00. externally triggered: True>
[2024-12-02T08:23:10.092+0000] {logging_mixin.py:190} INFO - Failure caused by "['genres_genres_6_text'] not in index"
[2024-12-02T08:23:10.093+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=IMDB_testing_DAG, task_id=transform, run_id=manual__2024-12-02T08:23:03.329268+00:00, execution_date=20241202T082303, start_date=20241202T082309, end_date=20241202T082310
[2024-12-02T08:23:10.119+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-02T08:23:10.120+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 54 for task transform ("['genres_genres_6_text'] not in index"; 11165)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/app/src/transform/transform.py", line 106, in transform
    rename_selected_df = rename_column(df)
                         ^^^^^^^^^^^^^^^^^
  File "/opt/airflow/app/src/transform/transform.py", line 17, in rename_column
    rename_selected_df = df[columns].copy()
                         ~~^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6179, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['genres_genres_6_text'] not in index"
[2024-12-02T08:23:10.157+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-02T08:23:10.190+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-02T08:23:10.195+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
